name: Ignore NuGet package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  NuGetPack:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release  /p:PublicRelease=true
    - name: Push package to NuGet
      run: dotnet nuget push .\src\Ignore\bin\Release\Ignore.*.nupkg --api-key ${{ secrets.nugetKey }} --source https://api.nuget.org/v3/index.json
