name: PR build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and test
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ignore/app:latest
  
  Tests:
    runs-on: ubuntu-latest
    container:
      image: ignore/app:latest
      options: -v ./coverage/:/coverage/:rw
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Push coverage to codecov
        run: bash <(curl -s https://codecov.io/bash) -s ./coverage
