name: PR build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        id: docker_build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          docker build -t ignore/app:latest .
          docker run -v ./coverage/:/coverage/:rw ignore/app:latest
          bash <(curl -s https://codecov.io/bash) -s ./coverage
